[[tasks]]
name = "Fight Event Stage"
type = "Fight"
strategy = "merge"

[tasks.params]
report_to_penguin = true
penguin_id = "001620106"

# use all expiring medicine on Sunday Evening
[[tasks.variants]]
params = { expiring_medicine = 1000 }

[tasks.variants.condition]
type = "And"
conditions = [
  { type = "Time", start = "18:00:00" },
  { type = "Weekday", weekdays = ["Sun"] },
]

[[tasks.variants]]
params = { stage = "1-7" }

[[tasks.variants]]
params = { stage = "BP-6" }
condition = { type = "OnSideStory", client = "Official" }
