[[tasks]]
type = "Roguelike"

[tasks.params]
theme = "Sami"

# Don't enter the second floor when the investment mode is enabled.
#investment_with_more_score = true

roles = "取长补短"
use_support = true
use_nonfriend_support = true

[tasks.params.mode]
alternatives = [0, 1, 4]
default_index = 1
description = "a fighting mode (1: point , 2: investmentm, 3: stop at floor 3)"

[tasks.params.core_char]
alternatives = ["百炼嘉维尔", "焰影苇草"]
default_index = 2
description = "a character"

[tasks.params.squad]
alternatives = ["指挥分队", "集群分队", "后勤分队", "特训分队"]
default_index = 4
description = "squad choose"

[[tasks]]
type = "CloseDown"
