[language-server.texlab.config.texlab]
forwardSearch.executable = 'zathura'
forwardSearch.args = ['--synctex-forward', '%l:1:%f', '%p']

[language-server.texlab.config.texlab.build]
executable = 'latexmk'
args = ['-pdfxe', '-interaction=nonstopmode', '-synctex=1', '%f']
onSave = true
forwardSearchAfter = true
